service: workuj-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: api/jobs  # Odstraňte duplicitní /prod
          method: get
          cors: true
      - http:
          path: api/jobs/{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.workuj.cz
    stage: ${self:provider.stage}
    basePath: prod  # Toto nastaví basePath na 'prod'
    createRoute53Record: true